### ISSUE TITLE
Kanun metnindeki "kitap", "kısım", "bölüm", "ayrım" gibi gruplandırmalar

### ISSUE THREAD

**Issue by ersagunkuruca** [anonrig/turk-medeni-kanunu-json#1]
Bir ucundan tutayım dedim ama kanun metnindeki bu gruplandırmaları nasıl bir nesting kullanarak aktarmamız lazım, bilemedim. Çünkü bazı "bölüm"lerin "ayrım"ları var bazılarının yok, ayrıca örnek olarak yaptığın ilk section(başlangıç) bir "kitap"a dahil değil. Ayrıca metnin ilerleyen kısımlarında bold olmayıp, bold olan **MADDE _n_**.'ler için başlık gibi görev gören yapılar var. Sanki bir yandan hiyerarşik bir başlık alt başlık sistemi var bir yandan da global bir madde numarası sistemi var gibi. Henüz tam çözemedim. Yapıyı tam oturtmak lazım. Hatta hazır yapmışken bütün kanunlara uygulanabilecek bir yapı oluşturursak, sadece Medeni Kanun'u değil bütün kanunları JSON formatına çevirecek bir script yazmak daha kolay olur.

**Comment by anonrig** [comment]
HTML versiyonunda herhangi bir hiyerarsi olmadigi icin bir script yazilamiyor, ne yazik ki. Karsimiza cikan sorunlara gore yapiyi tekrar duzeltmemiz gerekebilir. 1000 adet madde oldugu icin bunlari onceden gormek pek mumkun degil. Yapiyi degistirmemiz gerektiginde text editor'larin search & replace ozelligini kullanabiliriz.

**Comment by ersagunkuruca** [comment]
Peg.js ile parse etmeyi denedim bugün. Bayağı zor oldu. Orijinal metindeki bir takım sıkıntıları elle düzeltmek gerekti. Son hazırladığım dosyada JSON nesnelerinin property isimlerini (biraz tembellikten biraz da isimlendirememekten) tek harfli olarak verdim, kolaylıkla düzeltilebilir. Hiyerarşik yapıda sadece sonlara doğru genel yapıya uymayan bir iki şey eksik, onun dışında o da tam gibi duruyor. ersagunkuruca/turk-medeni-kanunu-json@bc9f6c582b9667c0216b4d6b9e7fe191b2b3c52f 'a koydum. Bir göz at, beğenirsen buradan yola çıkarız.

Edit: "Başlangıç" kısmı da eksik çıkmış, fark etmemişim.
